//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaivyBeatsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int musician_id { get; set; }
        public int restaurant_id { get; set; }
        public string follow_date { get; set; }
        public string delete_date { get; set; }
    }
}
