//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaivyBeatsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int publication_id { get; set; }
        public string publication_date { get; set; }
        public string description { get; set; }
        public string multimedia_content { get; set; }
        public int user_id { get; set; }
        public string titulo { get; set; }
    }
}
